package isw2.rrmasg.test.persistence;

import isw2.rrmasg.domain.DomainFactory;
import isw2.rrmasg.domain.song.ISong;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.junit.Test;

public class LoadSongs {

	@Test
	public void loadSongs() {
		EntityManagerFactory emf = Persistence
				.createEntityManagerFactory("wimbi");
		EntityManager em = emf.createEntityManager();
		em.getTransaction().begin();
		ISong s1 = DomainFactory.createTestSong();
		s1.setTitle("Because");
		s1.setAuthor("The Beatles");
		s1.setRecord("Apple");
		s1.setUrl("http://");
		em.persist(s1);
		ISong s2 = DomainFactory.createTestSong();
		s2.setTitle("Get Back");
		s2.setAuthor("The Beatles");
		s2.setRecord("Apple");
		s2.setUrl("http://");
		em.persist(s2);
		ISong s3 = DomainFactory.createTestSong();
		s3.setTitle("Glass Onion");
		s3.setAuthor("The Beatles");
		s3.setRecord("Apple");
		s3.setUrl("http://");
		em.persist(s3);
		ISong s4 = DomainFactory.createTestSong();
		s4.setTitle("Julia");
		s4.setAuthor("The Beatles");
		s4.setRecord("Apple");
		s4.setUrl("http://");
		em.persist(s4);
		ISong s5 = DomainFactory.createTestSong();
		s5.setTitle("I Am the Walrus");
		s5.setAuthor("The Beatles");
		s5.setRecord("Apple");
		s5.setUrl("http://");
		em.persist(s5);
		ISong s6 = DomainFactory.createTestSong();
		s6.setTitle("I Want To Hol Your Hand");
		s6.setAuthor("The Beatles");
		s6.setRecord("Apple");
		s6.setUrl("http://");
		em.persist(s6);
		ISong s7 = DomainFactory.createTestSong();
		s7.setTitle("Drive My Car");
		s7.setAuthor("The Beatles");
		s7.setRecord("Apple");
		s7.setUrl("http://");
		em.persist(s7);
		ISong s8 = DomainFactory.createTestSong();
		s8.setTitle("Gnik Nus");
		s8.setAuthor("The Beatles");
		s8.setRecord("Apple");
		s8.setUrl("http://");
		em.persist(s8);
		ISong s9 = DomainFactory.createTestSong();
		s9.setTitle("Something");
		s9.setAuthor("The Beatles");
		s9.setRecord("Apple");
		s9.setUrl("http://");
		em.persist(s9);
		ISong s10 = DomainFactory.createTestSong();
		s10.setTitle("Being for the Benefit of Mr. Kite!");
		s10.setAuthor("The Beatles");
		s10.setRecord("Apple");
		s10.setUrl("http://");
		em.persist(s10);
		ISong s11 = DomainFactory.createTestSong();
		s11.setTitle("Help!");
		s11.setAuthor("The Beatles");
		s11.setRecord("Apple");
		s11.setUrl("http://");
		em.persist(s11);
		ISong s12 = DomainFactory.createTestSong();
		s12.setTitle("Yesterday");
		s12.setAuthor("The Beatles");
		s12.setRecord("Apple");
		s12.setUrl("http://");
		em.persist(s12);
		ISong s13 = DomainFactory.createTestSong();
		s13.setTitle("Strawberry Fields Forever");
		s13.setAuthor("The Beatles");
		s13.setRecord("Apple");
		s13.setUrl("http://");
		em.persist(s13);
		ISong s14 = DomainFactory.createTestSong();
		s14.setTitle("Within You Without You");
		s14.setAuthor("The Beatles");
		s14.setRecord("Apple");
		s14.setUrl("http://");
		em.persist(s14);
		ISong s15 = DomainFactory.createTestSong();
		s15.setTitle("Lucy in the Sky with Diamonds");
		s15.setAuthor("The Beatles");
		s15.setRecord("Apple");
		s15.setUrl("http://");
		em.persist(s15);
		ISong s16 = DomainFactory.createTestSong();
		s16.setTitle("Octopus's Garden");
		s16.setAuthor("The Beatles");
		s16.setRecord("Apple");
		s16.setUrl("http://");
		em.persist(s16);
		ISong s17 = DomainFactory.createTestSong();
		s17.setTitle("Lady Madonna");
		s17.setAuthor("The Beatles");
		s17.setRecord("Apple");
		s17.setUrl("http://");
		em.persist(s17);
		ISong s18 = DomainFactory.createTestSong();
		s18.setTitle("Here Comes The Sun");
		s18.setAuthor("The Beatles");
		s18.setRecord("Apple");
		s18.setUrl("http://");
		em.persist(s18);
		ISong s19 = DomainFactory.createTestSong();
		s19.setTitle("Dear Prudence");
		s19.setAuthor("The Beatles");
		s19.setRecord("Apple");
		s19.setUrl("http://");
		em.persist(s19);
		ISong s20 = DomainFactory.createTestSong();
		s20.setTitle("Revolution");
		s20.setAuthor("The Beatles");
		s20.setRecord("Apple");
		s20.setUrl("http://");
		em.persist(s20);
		ISong s21 = DomainFactory.createTestSong();
		s21.setTitle("Back In The U.S.S.R.");
		s21.setAuthor("The Beatles");
		s21.setRecord("Apple");
		s21.setUrl("http://");
		em.persist(s21);
		ISong s22 = DomainFactory.createTestSong();
		s22.setTitle("While My Guitar Gently Weeps");
		s22.setAuthor("The Beatles");
		s22.setRecord("Apple");
		s22.setUrl("http://");
		em.persist(s22);
		ISong s23 = DomainFactory.createTestSong();
		s23.setTitle("A Day in the Life");
		s23.setAuthor("The Beatles");
		s23.setRecord("Apple");
		s23.setUrl("http://");
		em.persist(s23);
		ISong s24 = DomainFactory.createTestSong();
		s24.setTitle("Hey Jude");
		s24.setAuthor("The Beatles");
		s24.setRecord("Apple");
		s24.setUrl("http://");
		em.persist(s24);
		ISong s25 = DomainFactory.createTestSong();
		s25.setTitle("Sgt. Pepper's Lonely Hearts Club Band (Reprise)");
		s25.setAuthor("The Beatles");
		s25.setRecord("Apple");
		s25.setUrl("http://");
		em.persist(s25);
		ISong s26 = DomainFactory.createTestSong();
		s26.setTitle("All You Need Is Love");
		s26.setAuthor("The Beatles");
		s26.setRecord("Apple");
		s26.setUrl("http://");
		em.persist(s26);
		em.getTransaction().commit();
		em.close();
		emf.close();
	}

}
